import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useContext, useEffect, useState } from "react";
import { GameContext } from "@/context/GameContext";
import { db } from "@/firebase/config";
import { doc, getDoc } from "firebase/firestore";
import { AuthContext } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useContext(AuthContext);
  const { character, setNewCharacter } = useContext(GameContext);
  const [location, setLocation] = useState<any | null>(null);

  useEffect(() => {
    async function fetchCharacter() {
      if (!user) {
        return;
      }
      const docRef = doc(db, "users", user.uid);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        setNewCharacter(docSnap.data().character);
      } else {
        console.log("No such document!");
      }
    }
    fetchCharacter();
  }, [user]);

  useEffect(() => {
    async function getCharPos() {
      if (!character) {
        return;
      }
      const docRef = doc(db, "galaxy", character.star);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        setLocation(docSnap.data());
      } else {
      }
    }
    getCharPos();
  }, [character]);
  return (
    <>
      <Head>
        <title>Rpg</title>
        <meta name="Fantasy Rpg" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {location && character && (
            <p>
              {character.planet == 500
                ? location.name
                : character.city == 500
                ? location.planets[character.planet].name
                : location.planets[character.planet].cities[character.city]
                    .name}
            </p>
          )}
        </div>
      </main>
    </>
  );
}
